name: python
on:
  push:
    paths:
      - "main/py3-*/**"
  workflow_dispatch:

jobs:
  python3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #alpine_version: [v3.13, v3.14, v3.15]
        alpine_version: [v3.16, v3.17]
        alpine_arch: [x86_64, armhf, aarch64, armv7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Install Deploy SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Synchronize Repository Packages
        run: rsync -avz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main" ${HOME}/packages

      - name: Build jsonpickle Package
        run: docker run --rm -e "RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}" -v "${{ github.workspace }}/main/py3-jsonpickle:/home/builder/main/package" -v "${HOME}/packages:/packages" asymworks/alpine-abuild-${{ matrix.alpine_arch }}:${{ matrix.alpine_version }}

      - name: Build digitalocean Package
        run: docker run --rm -e "RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}" -v "${{ github.workspace }}/main/py3-digitalocean:/home/builder/main/package" -v "${HOME}/packages:/packages" asymworks/alpine-abuild-${{ matrix.alpine_arch }}:${{ matrix.alpine_version }}

      - name: Publish Repository Packages
        run: rsync -avz ~/packages/main/${{ matrix.alpine_arch }}/./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main/${{ matrix.alpine_arch }}/"
