name: vector
on:
  push:
    paths:
      - "main/vector/**"
  workflow_dispatch:

jobs:
  vector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alpine_version: [v3.22]
        alpine_arch: [x86_64, aarch64]

    steps:
      - uses: actions/checkout@v2

      - name: Configure Cache Env
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Check Cache Env
        run: |
          env
          echo "${{ ACTIONS_CACHE_URL }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Install Deploy SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Synchronize Repository Packages
        run: rsync -avz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main" ${HOME}/packages

      - name: Build Package
        run: |
          docker run --rm \
            -e "RSA_PRIVATE_KEY=${{ secrets.RSA_PRIVATE_KEY }}" \
            -e "ACTIONS_CACHE_URL=${{ ACTIONS_CACHE_URL }}" \
            -e "ACTIONS_RUNTIME_TOKEN=${{ ACTIONS_RUNTIME_TOKEN }}"
            -e SCCACHE_GHA_ENABLED=on \
            -v "${{ github.workspace }}/main/vector:/home/builder/main/package" \
            -v "${HOME}/packages:/packages" \
            asymworks/alpine-abuild-${{ matrix.alpine_arch }}:${{ matrix.alpine_version }}

      - name: Publish Repository Packages
        run: rsync -avz ~/packages/main/${{ matrix.alpine_arch }}/./ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/pkg/webroot/alpine/${{ matrix.alpine_version }}/main/${{ matrix.alpine_arch }}/"
